Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [ ]:
# Answer 01...

# A1. Yes, there is a difference in the data type of variables list_ and array_list. list_ is a list of strings while array_list is a numpy array of string type.

print(type(list_))
print(type(array_list))


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

# A2. The code to print the data type of each and every element of both variables list_ and array_list is:

for element in list_:
    print(type(element))

for element in array_list:
    print(type(element))


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [ ]:
# A3. Yes, there will be a difference in the data type of the elements present in both variables, list_ and array_list. After the modification of dtype to int, the elements in array_list will be of integer type.

# The code to print the data types of each and every element present in both the variables, list_ and array_list, after the modification is:

array_list = np.array(object = list_, dtype = int)

for element in list_:
    print(type(element))

for element in array_list:
    print(type(element))


Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [7]:
# Answer 4...
import numpy as np

In [10]:
num_list = [[1,2,3],[4,5,6]]


In [11]:
num_array = np.array(object = num_list)

In [12]:
print(num_array.shape)
print(num_array.size)

(2, 3)
6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [13]:
# Answer 5....

zeros_array = np.zeros(shape=(3,3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [14]:
# Answer 6 ...

identity_matrix = np.identity(n=5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
